modLoader="javafml" #mandatory
loaderVersion="[47,)"
license="MIT License https://github.com/McJtyMods/LostWorlds/blob/main/LICENSE"
[[mods]]
modId="lostworlds"
version="${file.jarVersion}"
displayName="LostRuins"
description='''
Worlds made for Lost Cities
'''
[[dependencies.lostworlds]]
    modId="forge" #mandatory
    mandatory=true
    versionRange="[40.1.50,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.lostworlds]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.lostworlds]]
    modId="lostcities"
    mandatory=true
    versionRange="[1.20-7.0.4,)"
    ordering="AFTER"
    side="BOTH"
